# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .get_arn import *
from .get_availability_zone import *
from .get_availability_zones import *
from .get_billing_service_account import *
from .get_caller_identity import *
from .get_default_tags import *
from .get_ip_ranges import *
from .get_partition import *
from .get_region import *
from .get_regions import *
from .get_service import *
from .provider import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_aws.config as __config
    config = __config
    import pulumi_aws.iam as __iam
    iam = __iam
    import pulumi_aws.x as __x
    x = __x
else:
    config = _utilities.lazy_import('pulumi_aws.config')
    iam = _utilities.lazy_import('pulumi_aws.iam')
    x = _utilities.lazy_import('pulumi_aws.x')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "aws",
  "mod": "iam/accessKey",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/accessKey:AccessKey": "AccessKey"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/accountAlias",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/accountAlias:AccountAlias": "AccountAlias"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/accountPasswordPolicy",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/accountPasswordPolicy:AccountPasswordPolicy": "AccountPasswordPolicy"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/group",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/group:Group": "Group"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/groupMembership",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/groupMembership:GroupMembership": "GroupMembership"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/groupPolicy",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/groupPolicy:GroupPolicy": "GroupPolicy"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/groupPolicyAttachment",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/groupPolicyAttachment:GroupPolicyAttachment": "GroupPolicyAttachment"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/instanceProfile",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/instanceProfile:InstanceProfile": "InstanceProfile"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/openIdConnectProvider",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/openIdConnectProvider:OpenIdConnectProvider": "OpenIdConnectProvider"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/policy",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/policy:Policy": "Policy"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/policyAttachment",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/policyAttachment:PolicyAttachment": "PolicyAttachment"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/role",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/role:Role": "Role"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/rolePolicy",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/rolePolicy:RolePolicy": "RolePolicy"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/rolePolicyAttachment",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/rolePolicyAttachment:RolePolicyAttachment": "RolePolicyAttachment"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/samlProvider",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/samlProvider:SamlProvider": "SamlProvider"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/serverCertificate",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/serverCertificate:ServerCertificate": "ServerCertificate"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/serviceLinkedRole",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/serviceLinkedRole:ServiceLinkedRole": "ServiceLinkedRole"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/serviceSpecificCredential",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/serviceSpecificCredential:ServiceSpecificCredential": "ServiceSpecificCredential"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/signingCertificate",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/signingCertificate:SigningCertificate": "SigningCertificate"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/sshKey",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/sshKey:SshKey": "SshKey"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/user",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/user:User": "User"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/userGroupMembership",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/userGroupMembership:UserGroupMembership": "UserGroupMembership"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/userLoginProfile",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/userLoginProfile:UserLoginProfile": "UserLoginProfile"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/userPolicy",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/userPolicy:UserPolicy": "UserPolicy"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/userPolicyAttachment",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/userPolicyAttachment:UserPolicyAttachment": "UserPolicyAttachment"
  }
 },
 {
  "pkg": "aws",
  "mod": "iam/virtualMfaDevice",
  "fqn": "pulumi_aws.iam",
  "classes": {
   "aws:iam/virtualMfaDevice:VirtualMfaDevice": "VirtualMfaDevice"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "aws",
  "token": "pulumi:providers:aws",
  "fqn": "pulumi_aws",
  "class": "Provider"
 }
]
"""
)
